### ISSUE TITLE
Cant add virtual directory to application(as distinct from web site)

### ISSUE THREAD

**Issue by endakenny** [opscode-cookbooks/iis#101]
Adding a virtual directory now works for me - for example this resource works without issue:

*iis_vdir 'Testfu Site/' do
	action :add
	path '/Content'
	physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
end*

 However when i try to add a virtual directory beneath an application as follows()where the application is simply called '1':

*iis_vdir 'Testfu Site/1/' do
	action :add
	path '/Content'
	physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
end*

it produces an appcmd command that has an additional trailing slash on the app.name:
*Ran C:\Windows\System32\inetsrv\appcmd.exe add vdir /app.name:"Testfu Site/1/" /path:"/Content" /physicalPath:"C:\inetpub\wwwroot\testfu\Content" /logonMethod:C
learText /allowSubDirConfig:true returned 50*

Naturally then i tried to remove the trailing slash (in iis_vdir). So my new resource is 

*iis_vdir 'Testfu Site/1' do
	action :add
	path '/Content'
	physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
end*

It results in this error:

*[2015-01-06T11:46:35+00:00] FATAL: NoMethodError: iis_vdir[Testfu Site/1] (testing-new-iis-cookbook::default line 87) had an error: NoMethodError:
hod `application_name=' for Chef::Resource::IisVdir*

Tried this also but no dice:

*iis_vdir 'Testfu Site/1/' do
	action :add
	path 'Content'
	physical_path "C:\\inetpub\\wwwroot\\testfu\\Content"
end*

I also tried explicitly setting the application_name with (application_name "Testfu Site/1/") and without (application_name "Testfu Site/1") while keeping the iis_vdir with its trailing slash(iis_vdir("Testfu Site/1/"))

Perhaps I'm doing something wrong - hopefully I'm not but would be great if someone could take a look and let me know what you think.

**Comment by EasyAsABC123** [comment]
@endakenny you are correct, thanks for finding this, working on a fix as I type this.  In the future please add @EasyAsABC123 so that i'll get an email notifying me of the bug.

**Comment by endakenny** [comment]
@EasyAsABC123  - yep  - will do in future - wasnt sure of the the division of responsibility as it a 'community' cookbook. Thanks for your help - i have now incorporated many iis_vdir resources into my main cookbook that uses iis and its working like a charm!

**Comment by EasyAsABC123** [comment]
@endakenny sounds good, I personally am making sure that v3.0.x is released.  This means that bugs should at least mention me.  Someone else might provide a fix, but i'd like to be notified.

Testing the fix now

**Comment by EasyAsABC123** [comment]
Fixed pushed to https://github.com/EasyAsABC123/iis/tree/hotfix_helper-class iis@3.0.9

**Comment by EasyAsABC123** [comment]
resolved #96

**Comment by endakenny** [comment]
@EasyAsABC123  - excellent - i have incorporated this into my cookbook and all works well. I owe you one!

**Comment by EasyAsABC123** [comment]
@endkenny awesome news, let me know if you find any other issues so we can resolve them as quickly as possible.

Justin Schuhmann
