### ISSUE TITLE
mod_management on 2012r2 requires dism /all flag

### ISSUE THREAD

**Issue by academy-jtran** [opscode-cookbooks/iis#103]
https://github.com/opscode-cookbooks/iis/pull/102

Please see above pull request

**Comment by EasyAsABC123** [comment]
@academy-jtran in general you don't need to make an issue that is simply so you can point it to a pull request.  This is where you should be putting errors and examples of how to duplicate those errors.

**Comment by ksubrama** [comment]
Fixed.
