### ISSUE TITLE
Compile issue because of encoding on libraries\matcher.rb

### ISSUE THREAD

**Issue by EasyAsABC123** [opscode-cookbooks/iis#104]
@smurawski
```
knife cookbook upload iis
Uploading iis            [3.0.10]
FATAL: Cookbook file libraries/matcher.rb has a ruby syntax error:
FATAL: /Users/justin/Documents/Code/chef/chef-repo/.chef/../cookbooks/iis/libraries/matcher.rb:70: syntax error, unexpected keyword_end, expecting $end
```

output of od -c matcher.rb
```
0000000  357 273 277   i   f       d   e   f   i   n   e   d   ?   (   C
```

`357 273 277` shouldn't be there

apparently multiple files have this now, due to encoding them in Notepad++ as UTF-8

**Comment by smurawski** [comment]
A clean checkout of the repository seems to work fine for me on a Server 2012 R2 box.  Reclone?

**Comment by smurawski** [comment]
Are you doing any autocrlf management?

**Comment by EasyAsABC123** [comment]
We are digging into this deeper, we run Mac OS X but are going to test this on windows, mac, and linux

**Comment by smurawski** [comment]
Yeah, it has to be BOM oddness.  Re-saving the file as UTF8 in Sublime on the Mac allowed it to pass knife cookbook test.

**Comment by smurawski** [comment]
UTF-8 without BOM that is.  The byte order mark is what is causing the blow up.

**Comment by EasyAsABC123** [comment]
Yeah it looks like my ~/profile is set to UTF-8 instead of 
encoding=utf-8 nobomb

I'll correct this as to avoid this in the future

**Comment by jeremymv2** [comment]
Yep, BOM is the culprit.

jeremymiller-> head -c 3 libraries/matcher.rb | od -t x1
0000000    ef  bb  bf
0000003

It was in multiple files.  I put together a couple of command to find recursively and fix:
for f in `find . -type f`; do ret=`head -c 3 $f | od -t x1 | grep -c "ef  bb  bf"`; if [ $ret -eq 1 ]; then awk 'NR==1{sub(/^\xef\xbb\xbf/,"")}1' $f > $f.new; mv $f.new $f; fi; done

Justin, I committed to the hotfix_helper-class branch.

**Comment by EasyAsABC123** [comment]
There is a fix I'll submit a pull request shortly

**Comment by EasyAsABC123** [comment]
@smurawski pull request added, Jeremy fixed the issue.
