### ISSUE TITLE
iis_app resource - cant change an applications physical path

### ISSUE THREAD

**Issue by endakenny** [opscode-cookbooks/iis#106]
So i would like to use the iis_app resource to change the physical path on disk that the IIS application points to. 
If this functionality is there an example of how to do this would be great. 
If not could the functionality be added?

Here is how i imagine it would look - with a config action perhaps:

*iis_app "contoso" do
  path "/1"
  application_pool "myAppPool_v1_1"
  physical_path "C:\\contoso\\1\\repointed"
  action :config
end*

when i use the add variant:

*iis_app "contoso" do
  path "/1"
  application_pool "myAppPool_v1_1"
  physical_path "C:\\contoso\\1\\repointed"
  action :add
end*

#I get this error:

---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe add app /site.name:"contoso" /path:"/1" /applicationPool:"myAppPool_v1_1" /physicalPath:"C:\\contoso\\1\\repointed" ----
ERROR ( message:Failed to add duplicate collection element "/fw7/1". )

**Comment by endakenny** [comment]
My apologies - i see now that this should covered virtual directory resources rather than the app resources. I discovered what i think is a bug in that. Ill log a new issue

**Comment by EasyAsABC123** [comment]
@endakenny I think this is a bug in iis_app, but if you think it is in vdir feel free to post the issue with error.

thanks

**Comment by endakenny** [comment]
Just posted now(#107) - all the details should be included. In appcmd -
this can be done with 'appcmd set vdir' so i imagine it should logically
sit in the IIS cookbook iis_vdir resource.
