### ISSUE TITLE
iis_vdir - config action appears to ignore the physical_path when constructing appcmd command

### ISSUE THREAD

**Issue by endakenny** [opscode-cookbooks/iis#107]
Here is my resource:

*iis_vdir "teste env1 f/" do
	path '/fw7/1/'
	physical_path "C:\\Websites\\teste\\env1\\f\\fw7\\repointed"
	action :config
end*

It returns a message as to say it completed successfully but it did not change the physical path of the application ("teste env1 f/fw7/1"). 

I would expect that it would produce this appcmd (which when i run manually does change the physical path)
*appcmd.exe set vdir "teste env1 f/fw7/1/" -physicalPath:C:\\Websites\\teste\\env1\\f\\fw7\\repointed /logonMethod:ClearText*

Before i got this 'working' i had omitted a trailing slash in the path. This error highlighted the fact that the physicalPath appears to be discarded as the code builds up the appcmd command.

================================================================================
Error executing action `config` on resource 'iis_vdir[teste env1 f/]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '50'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe set vdir "teste env1 f/fw7/1" /logonMethod:ClearText ----
STDOUT: ERROR ( message:Must use exact identifer for VDIR object with verb SET. )
STDERR:
---- End output of `C:\Windows\System32\inetsrv\appcmd.exe set vdir "teste env1 f/fw7/1" /logonMethod:ClearText` ----
Ran C:\Windows\System32\inetsrv\appcmd.exe set vdir "teste env1 f/fw7/1" /logonMethod:ClearText returned 50

Resource Declaration:
---------------------
In C:/chef/.chef/local-mode-cache/cache/cookbooks/testing-iisapppath/recipes/default.rb

 18: iis_vdir "teste env1 f/" do
 19:        path '/fw7/1'
 20:   physical_path 'C:\\Websites\\teste\\env1\\f\\fw7\\repointed'
 21:   action :config
 22: end
 23:

Compiled Resource:
------------------
Declared in C:/chef/.chef/local-mode-cache/cache/cookbooks/testing-iisapppath/recipes/default.rb:18:in `from_file'

iis_vdir("teste env1 f/") do
  action [:config]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :iis_vdir
  cookbook_name "testing-iisapppath"
  recipe_name "default"
  path "/fw7/1"
  physical_path "C:\\Websites\\teste\\env1\\f\\fw7\\repointed"
  application_name "teste env1 f/"
  logon_method :ClearText
  allow_sub_dir_config true
end

**Comment by EasyAsABC123** [comment]
@endakenny if you give the `iis_vdir` provider the following command will run

```ruby
cmd = "#{appcmd(node)} set vdir \"#{application_identifier}\" /physicalPath:\"#{@new_resource.physical_path}\""
```

which in your example should become:
```ruby
cmd = "C:\Windows\System32\inetsrv\appcmd.exe set vdir \"teste env1 f/fw7/1\" /physicalPath:\"C:\Websites\teste\env1\f\fw7\repointed\""
```

**Comment by EasyAsABC123** [comment]
@endakenny the error appears to be this:

```
In C:/chef/.chef/local-mode-cache/cache/cookbooks/testing-iisapppath/recipes/default.rb

18: iis_vdir "teste env1 f/" do
19: path '/fw7/1'
20: physical_path 'C:\Websites\teste\env1\f\fw7\repointed'
21: action :config
22: end
23:
```
this should be
```
iis_vdir "teste env1 f/" do
  path '/fw7/1/'
  physical_path 'C:\Websites\teste\env1\f\fw7\repointed'
  action :config
end
```

you need the path to end with `/`

**Comment by endakenny** [comment]
@EasyAsABC123. Perhaps i have confused the issue with how i presented it. 

I am aware that i had omitted a trailing slash - see above "Before i got this 'working' i had omitted a trailing slash in the path. This error highlighted the fact that the physicalPath appears to be discarded as the code builds up the appcmd command."
So this was was my second last attempted before i got the recipe to run without error

So at the very top is my 'working' resource - chef runs without error but the physicalPath remains unchanged. 

The reason i included this 'broken' resource it because the stack trace show that the physical_path though compiled  correctly - is not uses in the resultant appcmd:

# C:\Windows\System32\inetsrv\appcmd.exe set vdir "teste env1 f/fw7/1" /logonMethod:ClearText

Re your fist post (if you give the iis_vdir provider the following command will run) - would you mind altering my resource (the 'working' one ) so that it 'gives the iis_vdir provider' what it wants?

**Comment by EasyAsABC123** [comment]
@endakenny  I don't see where `/logonMethod:ClearText` is coming from

**Comment by EasyAsABC123** [comment]
@endakenny if the error still occurs let me know and i'll write a quick test recipe to see if this is an internal error.

**Comment by endakenny** [comment]
Well to my mind it is quite correct that in the ruby recipe file its "C:\\Websites\\teste\\env1\\f\\fw7\\repointed" and that this is compiled without the double back slashes (as with this command which does what i want when run manually  - *appcmd.exe set vdir "teste env1 f/fw7/1/" -physicalPath:C:\Websites\teste\env1\f\fw7\repointed /logonMethod:ClearText* )as this is what appcmd(and windows) expects.

**Comment by EasyAsABC123** [comment]
The command you are getting to run is actually 

```
cmd = "#{appcmd(node)} set vdir \"#{application_identifier}\" /logonMethod:#{@new_resource.logon_method.to_s}"
```

which should only run if the logon_method changes

**Comment by EasyAsABC123** [comment]
working on a demo recipe right now, give me a few and i'll let you know if i find the issue

**Comment by endakenny** [comment]
Re logonMethod - its not concerning me right now

**Comment by EasyAsABC123** [comment]
can you please test the following branch? https://github.com/EasyAsABC123/iis/tree/hotfix-issue_with_helper this resolved the issue for me but it is a bug in one of the deep helper classes.

**Comment by endakenny** [comment]
@EasyAsABC123  - thank you - this seems to do the trick. Given that you say its a issue with the deeper helper classes, did you fix it there or work around somehow elsewhere. The reason i ask is because if its the latter then when the helper classes are fixed is it likely to break this version of the iis cookbook and my use of same in my cookbooks?

**Comment by EasyAsABC123** [comment]
@endakenny the deeper class was fixed, this resolved a lot of bugs that no one was noticing. Thank you for reporting this one as it led to the others
