### ISSUE TITLE
Update README for iis_app provider app_name attribute?

### ISSUE THREAD

**Issue by kenny-evitt** [opscode-cookbooks/iis#109]
I was able to add a new IIS Application to the existing site "Default Web Site" but I had to enter the name of the *site* as the `app_name` parameter.

**Comment by kenny-evitt** [comment]
Assuming I'm correct about the change that needs to be made (and that you're using GitHub Issues), would this qualify as an "obvious fix"?

**Comment by EasyAsABC123** [comment]
@kenny-evitt i'm confused, in the readme.md it states 
```
app_name - name attribute. The name of the site to add this app to
```

which means exactly what you are saying the app_name is set to the name of the site you are adding it to.

then the virtual path is what allows you to make the actual application name.  Do you want `app_name` renamed to `site_name`?

**Comment by kenny-evitt** [comment]
@EasyAsABC123 you're right that the documentation is technically correct. And, yes, all else equal, I think `app_name` should be renamed to `site_name`. But I imagine doing so might not be worth it if it breaks dependent recipes.

I was confused because I expected `app_name` to be the name of the *app*, even tho there is no real 'name' of an app in IIS apart from it's 'virtual path'.

Maybe "site" could be emphasized in the description of `app_name`.

**Comment by EasyAsABC123** [comment]
@kenny-evitt Since no one has a gun to anyone's head to upgrade I'd argue that if it is illogical in its current form it should be changed.

pull request opened, i'll work with @smurawski on Monday if needed.

**Comment by kenny-evitt** [comment]
@EasyAsABC123 thanks!
