### ISSUE TITLE
Deprecated RSpec message still showing

### ISSUE THREAD

**Issue by seeafish** [opscode-cookbooks/iis#119]
Due to dependencies, five deprecated messages appear every time rspec is run:
```
[DEPRECATION] `ChefSpec::Runner.define_runner_method' is deprecated. It is being used in the iis_app resource matcher. Please use `ChefSpec.define_matcher' instead.
[DEPRECATION] `ChefSpec::Runner.define_runner_method' is deprecated. It is being used in the iis_config resource matcher. Please use `ChefSpec.define_matcher' instead.
[DEPRECATION] `ChefSpec::Runner.define_runner_method' is deprecated. It is being used in the iis_module resource matcher. Please use `ChefSpec.define_matcher' instead.
[DEPRECATION] `ChefSpec::Runner.define_runner_method' is deprecated. It is being used in the iis_pool resource matcher. Please use `ChefSpec.define_matcher' instead.
[DEPRECATION] `ChefSpec::Runner.define_runner_method' is deprecated. It is being used in the iis_site resource matcher. Please use `ChefSpec.define_matcher' instead.
```
I believe this issue has been resolved in the master version of this cookbook, but supermarket is still locked to version 2.1.6.

I guess this not so much an issue but more a question of when you will release version 3.0.x of this cookbook to supermarket so that these messages will stop appearing.
Bear in mind anyone using the php cookbook will see these messages due to a dependency back to this cookbook.

**Comment by EasyAsABC123** [comment]
@seeafish iis@3 is being worked on diligently and the goal is to release it as quickly as possible.

@smurawski do you have a better answer for @seeafish

**Comment by seeafish** [comment]
Thanks for the quick answer @EasyAsABC123 
Any further information is appreciated! :)

**Comment by ksubrama** [comment]
I think this is now resolved since we released version 4 recently.
