### ISSUE TITLE
Compile error for site resource

### ISSUE THREAD

**Issue by znunez** [opscode-cookbooks/iis#125]
Recipe Compile Error in c:/chef/cache/cookbooks/iis/resources/site.rb

NameError

undefined local variable or method `iis' for #<Class:0x51b8098>

Cookbook Trace:

  c:/chef/cache/cookbooks/iis/resources/site.rb:32:in `class_from_file'

Relevant File Content:

c:/chef/cache/cookbooks/iis/resources/site.rb:

 25:  attribute :port, :kind_of => Integer, :default => 80
 26:  attribute :path, :kind_of => String
 27:  attribute :protocol, :kind_of => Symbol, :default => :http, :equal_to => [:http, :https]
 28:  attribute :host_header, :kind_of => String, :default => nil
 29:  attribute :bindings, :kind_of => String, :default => nil
 30:  attribute :application_pool, :kind_of => String, :default => nil
 31:  attribute :options, :kind_of => String, :default => ''
 32>> attribute :log_directory, :kind_of => String, :default => "#{iis['pubroot']}\\logs\\LogFiles"
 33:  attribute :log_period, :kind_of => Symbol, :default => :Daily, :equal_to => [:Daily, :Hourly, :MaxSize, :Monthly,
:Weekly]
 34:  attribute :log_truncsize, :kind_of => Integer, :default => 1048576
 35:
 36:  attr_accessor :exists, :running
 37:
 38:  def initialize(*args)
 39:    super
 40:    @action = :add
 41:  end

My attributes from the node are:

"iis": {
  "home": "C:\\Windows\\System32\\inetsrv",
  "conf_dir": "C:\\Windows\\System32\\inetsrv\\config",
  "pubroot": "C:\\inetpub",
  "docroot": "C:\\inetpub\\wwwroot",
  "log_dir": "C:\\inetpub\\logs\\LogFiles",
  "cache_dir": "C:\\inetpub\\temp",

Is there something I am missing?

Chef-client version = 11.12.4
iis cookbook version = 3.0.12

**Comment by EasyAsABC123** [comment]
Resolved by https://github.com/opscode-cookbooks/iis/pull/124

**Comment by znunez** [comment]
Thank you @EasyAsABC123 !!

**Comment by EasyAsABC123** [comment]
leave the issue open until #124 is pulled into master.

**Comment by EasyAsABC123** [comment]
pull request #124 is now in master, closing
