### ISSUE TITLE
host_header changes not applying on config

### ISSUE THREAD

**Issue by Novex** [opscode-cookbooks/iis#135]
Oops sorry, I did this backwards because admittedly I didn't read the contribution guidelines until after creating the pull request.

I noticed `host_header` changes would only take effect on add, not on `config`.

This seems to be because `is_new_port_host_provided` is checking to see if the binding combo is already included, which it never will be. This prevents the binding being added on line 79. This commit just flips the logic.

It also fixes an edge-case where a config change with a host-header of `localhost-foo` -> `localhost` wouldn't get applied (since technically `http/*:80:localhost` is included in `http/*:80:localhost-foo`).

**Comment by EasyAsABC123** [comment]
Resolved #134  and merged
