### ISSUE TITLE
iis_app config action - xpath incorrect

### ISSUE THREAD

**Issue by CaseyBurnsSv** [opscode-cookbooks/iis#142]
The xpath queries used to determine the current values do NOT work against the output from appcmd.exe.

For example; xpath = 'APP/application/virtualDirectory/@physicalPath'
But the output from appcmd.exe is wrapped in a root tag of <appcmd>

The xpath query never finds a match and assumes the resource is configured as expected.

Prefixing the xpath with '//' should fix the problem. But shouldn't it also throw if it cannot find the resource we are trying to apply the config to?

**Comment by EasyAsABC123** [comment]
which provider are you having issues with?

**Comment by CaseyBurnsSv** [comment]
app.rb

**Comment by CaseyBurnsSv** [comment]
Fork with fix: https://github.com/CaseyBurnsSv/iis/commit/0a10ef0c2fb676bf78c75e167b8a932079595447

**Comment by EasyAsABC123** [comment]
you sure about this? when i do a puts it is working.  this is the same for all of the stuff (used in all providers).  What IIS are you using, what OS are you using?

**Comment by CaseyBurnsSv** [comment]
Thanks for the fast response!

I am using Windows 8.1 and IIS 8.5.

When I run this: C:\windows\System32\inetsrv\appcmd.exe list app "abc" /config:* /xml

The result I see is has this structure:
<?xml version="1.0" encoding="UTF-8"?>
<appcmd>
    <APP >
        <application >
            <virtualDirectoryDefaults >
            <virtualDirectory >
        </application>
    </APP>
</appcmd>

**Comment by CaseyBurnsSv** [comment]
I might have found another issue -- now it is detecting that the app's physical path has changed. But it never reaches the code that executes appcmd.exe to update the physical path.

Line 73 of providers/app.rb -- cmd is null when is_new_physical_path is true.

**Comment by EasyAsABC123** [comment]
that's weird:
```ruby
if new_resource.physical_path && is_new_physical_path
        was_updated = true
        cmd = "#{appcmd(node)} set vdir /vdir.name:\"#{vdir_identifier}\""
        cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.physical_path)}\""
        Chef::Log.debug(cmd)
        shell_out!(cmd)
      end
```

are you on the latest version?

**Comment by EasyAsABC123** [comment]
ahh the bug is the if above it
```ruby
    if(cmd == nil)
      Chef::Log.debug("#{new_resource} application - nothing to do")
    else
      shell_out!(cmd)
      
      if ((new_resource.path && is_new_path) or
        (new_resource.application_pool && is_new_application_pool) or
        (new_resource.enabled_protocols && is_new_enabled_protocols))
        was_updated = true
      end

      if new_resource.physical_path && is_new_physical_path
        was_updated = true
        cmd = "#{appcmd(node)} set vdir /vdir.name:\"#{vdir_identifier}\""
        cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.physical_path)}\""
        Chef::Log.debug(cmd)
        shell_out!(cmd)
      end
      if was_updated
        new_resource.updated_by_last_action(true)
        Chef::Log.info("#{new_resource} configured application")
      else
        Chef::Log.debug("#{new_resource} application - nothing to do")
      end
    end
```

**Comment by EasyAsABC123** [comment]
missing an end much earlier in the code.  Try:

```ruby
if(cmd == nil)
      Chef::Log.debug("#{new_resource} application - nothing to do")
    else
      shell_out!(cmd)
was_updated = true
end

      if new_resource.physical_path && is_new_physical_path
        was_updated = true
        cmd = "#{appcmd(node)} set vdir /vdir.name:\"#{vdir_identifier}\""
        cmd << " /physicalPath:\"#{windows_cleanpath(new_resource.physical_path)}\""
        Chef::Log.debug(cmd)
        shell_out!(cmd)
      end
      if was_updated
        new_resource.updated_by_last_action(true)
        Chef::Log.info("#{new_resource} configured application")
      else
        Chef::Log.debug("#{new_resource} application - nothing to do")
      end
   
```

**Comment by CaseyBurnsSv** [comment]
Yeah, just tried that. Seems to fix it. I had to add a windows_cleanpath(x) on the attribute

**Comment by EasyAsABC123** [comment]
make sure you have this fix in a separate branch and make a new issue for it, i'll code review and pull it in

**Comment by CaseyBurnsSv** [comment]
I'll submit the fix when I get home tonight. In about 4 hours or so.

**Comment by CaseyBurns** [comment]
Please close this. I created it with my work GitHub account.

**Comment by EasyAsABC123** [comment]
Closing issue at the request of the OP
