### ISSUE TITLE
iis_pool issue when setting a gMSA identity

### ISSUE THREAD

**Issue by znunez** [opscode-cookbooks/iis#151]
I can no longer set gMSA accounts using iis_pool resource. These accounts do not have passwords, and it seems the pool provider is checking to ensure the pool_password is not an empty string. Setting pool_password to nil also does not work.

**Comment by EasyAsABC123** [comment]
You are correct, can you link to gMSA account types so that the upcoming patch can be written in the most uniform fashion.
