### ISSUE TITLE
iis_section unlock fails to unlock authentication section

### ISSUE THREAD

**Issue by pvandervelde** [opscode-cookbooks/iis#161]
In my cookbook I'm trying to unlock the IIS windowsAuthentication and anonymousAuthentication sections at the global level but somehow it is not working correctly. I'm running the cookbook against a Win2012R2 server and am installing IIS with the IIS cookbook (version 4.1.0):

    include_recipe 'iis'
    
    # Install the ASP.NET 4.5 runtime components
    include_recipe 'iis::mod_aspnet45'
    
    # Install the Windows authentication support
    include_recipe 'iis::mod_auth_windows'
    
    # install the HTTP logging, logging tools and custom logging
    include_recipe 'iis::mod_logging'
    
    # remove the default website
    include_recipe 'iis::remove_default_site'

All of that is working successfully.

The code in my cookbook to unlock the authentication sections is:

    iis_section 'system.webServer/security/authentication/anonymousAuthentication' do
      action :unlock
      section 'system.webServer/security/authentication/anonymousAuthentication'
    end
    
    iis_section 'system.webServer/security/authentication/windowsAuthentication' do
      action :unlock
      section 'system.webServer/security/authentication/windowsAuthentication'
    end

The cookbook runs to completion but the sections are just not unlocked.

I also have unlock sections for

    iis_section 'system.webServer/handlers' do
      section 'system.webServer/handlers'
      action :unlock
    end
    
    iis_section 'system.webServer/modules' do
      section 'system.webServer/modules'
      action :unlock
    end

These seem to be working correctly but the authentication section is not working. If I unlock the sections manually then it works. Like this:

    powershell_script 'unlock IIS authentication sections' do
      code <<-POWERSHELL
        $ErrorActionPreference = 'Stop'
    
        $appCmd = 'c:\\windows\\system32\\inetsrv\\appcmd.exe'
    
        & $appCmd unlock config -section:"system.webServer/security/authentication/anonymousAuthentication" -commit:apphost
        & $appCmd unlock config -section:"system.webServer/security/authentication/windowsAuthentication" -commit:apphost
      POWERSHELL
    end

From looking at the iis_section unlock code I think the `-commit:apphost` bit is missing (see http://serverfault.com/a/360556/239001)?

**Comment by EasyAsABC123** [comment]
@pvandervelde please test branch `bug-iis_section` or pull request #162

**Comment by pvandervelde** [comment]
I'm trying to push my changes to our production servers at the moment so I can't test this right now but I will do as soon as the release has been done.

**Comment by EasyAsABC123** [comment]
It won't work because of #163

**Comment by pvandervelde** [comment]
Just as an FYI. I tested it last week with version 4.1.1. and it still doesn't seem to work. Not quite sure what got unlocked but definitely not the configs that I wanted to have unlocked.

**Comment by EasyAsABC123** [comment]
@pvandervelde can you give more detail? what does your recipe look like?

thanks

**Comment by EasyAsABC123** [comment]
My assumption is the lack of `/commit:`, which i'll add.

**Comment by pvandervelde** [comment]
My current recipe looks like this:

    #
    # Cookbook Name:: monitoring_server
    # Recipe:: website
    #
    # Copyright 2015, Vista Entertainment Ltd.
    #
    # All rights reserved - Do Not Redistribute
    #

    include_recipe 'windows'
    include_recipe 'iis'
    # include_recipe 'webpi'

    # Install the ASP.NET 4.5 runtime components
    include_recipe 'iis::mod_aspnet45'

    # Install the Windows authentication support
    include_recipe 'iis::mod_auth_windows'

    # install the HTTP logging, logging tools and custom logging
    include_recipe 'iis::mod_logging'

    # remove the default website
    include_recipe 'iis::remove_default_site'

    # install Application Request Routing V3.0
    # webpi_product 'ARRv3_0' do
    #   accept_eula true
    #   action :install
    # end
    #
    # Install URL rewrite V2
    # webpi_product 'UrlRewrite2' do
    #   accept_eula true
    #   action :install
    # end

    # Copy the portal HTML index page
    portal_directory = node['paths']['devinfra_portal_base']
    remote_directory portal_directory do
      source 'portal'
      rights :read_execute, 'Everyone', applies_to_children: true, applies_to_self: false
      action :create
    end

    consul_ui_directory = node['paths']['devinfra_portal_consul']
    remote_directory consul_ui_directory do
      source 'consului'
      rights :read_execute, 'Everyone', applies_to_children: true, applies_to_self: false
      action :create
    end

    iis_section 'system.webServer/handlers' do
      section 'system.webServer/handlers'
      action :unlock
    end

    iis_section 'system.webServer/modules' do
      section 'system.webServer/modules'
      action :unlock
    end

    # Unlock the global authentication so that the authentication modes can be specified
    # by a web.config file. Note that we use a powershell section here to
    # handle the unlocking because there is an issue in the IIS cookbook which doesn't
    # unlock the authentication section at the right level.
    powershell_script 'unlock IIS authentication sections' do
      code <<-POWERSHELL
        $ErrorActionPreference = 'Stop'

        $appCmd = 'c:\\windows\\system32\\inetsrv\\appcmd.exe'

        & $appCmd unlock config -section:"system.webServer/security/authentication/anonymousAuthentication" -commit:apphost
        & $appCmd unlock config -section:"system.webServer/security/authentication/windowsAuthentication" -commit:apphost
      POWERSHELL
    end

    # Create an App pool for the portal
    # - Running with the standard IIS user
    # -.NET v4 integrated pipeline
    apppool_name = node['iis']['devinfra_portal_apppool']
    iis_pool apppool_name do
      runtime_version '4.0'
      pipeline_mode :Integrated
      pool_identity :ApplicationPoolIdentity
      action [:add, :start]
    end

    iis_site 'devinfrastructure_portal' do
      protocol :http
      port 80
      path portal_directory
      application_pool apppool_name
      action [:add, :start]
    end

This is using 4.1.1 of the IIS cookbook. I'm running the chef client locally on the machine if that makes a difference.

For some reason unlocking the `modules` and `handlers` section seems to work but the `authentication` sections can't be unlocked if I use the `iis_section`. I'm currently working on this recipe so if there is a (potential) fix for this let me know and I'll be happy to test. Just need to know what to do in order to get the IIS cookbook.

**Comment by EasyAsABC123** [comment]
I've been looking at this, the command you are executing via powershell is identical to the command being ran via command line.  Try running your command as a shell_out instead of powershell.  Be aware that this powershell method isn't idempotent so it is running this command every time you run this recipe.

I'll look a little deeper and make sure the appcmd.exe call is correct but it is identical to the one running in the recipe.

Go to providers/section to see the commands that it runs.

**Comment by pvandervelde** [comment]
I'll test it again on my current cookbook. Could well be that something else stuffed up. Will investigate

**Comment by EasyAsABC123** [comment]
Thanks, can you look in the providers/section.rb file and then under the unlock function check the command and see if it has commit in it? Let me know, thanks again.

Justin Schuhmann

**Comment by pvandervelde** [comment]
Here's what the unlock function looks like in the version of the IIS cookbook I have

    action :unlock do
      @current_resource.exists = new_value?(doc.root, 'CONFIG/@overrideMode', 'Allow')

      if !@current_resource.exists
        cmd = "#{appcmd(node)} unlock config -section:\"#{new_resource.section}\" -commit:apphost"
        Chef::Log.debug(cmd)
        shell_out!(cmd, returns: new_resource.returns)
        new_resource.updated_by_last_action(true)
        Chef::Log.info('IIS Config command run')
      else
        Chef::Log.debug("#{new_resource.section} already unlocked - nothing to do")
      end
    end

And I just ran my cookbook with the following items

    iis_section 'system.webServer/security/authentication/anonymousAuthentication' do
      section 'system.webServer/security/authentication/anonymousAuthentication'
      action :unlock
    end

    iis_section 'system.webServer/security/authentication/windowsAuthentication' do
      section 'system.webServer/security/authentication/windowsAuthentication'
      action :unlock
    end

and it didn't work. Not sure why or how, but I can't turn on the authentication in my website web.config because the sections aren't unlocked

**Comment by EasyAsABC123** [comment]
@pvandervelde can you open command line (as administrator) and run your PowerShell command?  this should unlock your sections and prove whether this is wrong or right.

**Comment by pvandervelde** [comment]
Ok so I just ran a cookbook with the following section in it:

    iis_section 'system.webServer/handlers' do
      section 'system.webServer/handlers'
      action :unlock
    end

    iis_section 'system.webServer/modules' do
      section 'system.webServer/modules'
      action :unlock
    end

    iis_section 'system.webServer/security/authentication/windowsAuthentication' do
      section 'system.webServer/security/authentication/windowsAuthentication'
      action :unlock
    end

    iis_section 'system.webServer/security/authentication/anonymousAuthentication' do
      section 'system.webServer/security/authentication/anonymousAuthentication'
      action :unlock
    end
    
    iis_config '-section:system.webServer/proxy /enabled:"True" /commit:apphost' do
      action :config
    end

So this should be unlocking 4 different sections and then it should run the iis_config element. The output log from chef gives me

    [2015-06-03T16:10:45+12:00] INFO: Processing iis_section[system.webServer/handlers] action unlock (monitoring_server::website line 49)
    [2015-06-03T16:10:45+12:00] INFO: IIS Config command run
    [2015-06-03T16:10:45+12:00] INFO: Processing iis_section[system.webServer/modules] action unlock (monitoring_server::website line 54)
    [2015-06-03T16:10:45+12:00] INFO: IIS Config command run
    [2015-06-03T16:10:45+12:00] INFO: Processing iis_section[system.webServer/security/authentication/windowsAuthentication] action unlock (monitoring_server::website line 59)
    [2015-06-03T16:10:46+12:00] INFO: Processing iis_section[system.webServer/security/authentication/anonymousAuthentication] action unlock (monitoring_server::website line 64)
    [2015-06-03T16:10:46+12:00] INFO: Processing iis_config[-section:system.webServer/proxy /enabled:"True" /commit:apphost] action config (monitoring_server::website line 84)
    [2015-06-03T16:10:46+12:00] INFO: IIS Config command run

Looking at the log it seems that the unlock for the authentication sections is never actually executed. Which would explain why it doesn't unlock those sections. Not sure why it's not being executed though. The code suggests that this means that the resource is already unlocked but I don't agree with that.

Something else I just spotted in the log was this: 

    [2015-06-03T16:09:24+12:00] INFO: Processing windows_feature[IIS-WindowsAuthentication] action install (iis::mod_auth_windows line 29)
    [2015-06-03T16:09:32+12:00] INFO: windows_feature[IIS-WindowsAuthentication] installed feature
    [2015-06-03T16:09:32+12:00] INFO: Processing iis_section[unlocks windows authentication control in web.config] action unlock (iis::mod_auth_windows line 33)

That seems to say it's unlocking the same section as above. If it is then that obviously failed too. Then again I might well be misunderstanding the log.

I hope this makes things more clear. Let me know if you need me to test more stuff.

**Comment by EasyAsABC123** [comment]
Thank you for these logs, can you run the chef client (fresh) with the debug flag?  This should give us all the required information.  

I will also be able to test this tonight and I am also running Win2012R2

**Comment by EasyAsABC123** [comment]
I actually don't have time tonight, I will get to this ASAP

**Comment by tylergohl** [comment]
Any progress on this?  Running into the same issue on 2008 r2

**Comment by EasyAsABC123** [comment]
@tylergohl I'll look at this over the weekend, but no currently there has been no progress on this.

**Comment by tylergohl** [comment]
Did a little more digging on this, it looks like the difference is the `overrideMode="Inherit"` versus `overrideMode="Allow"` when running manually.  I don't quite understand why that would be the case though.  As you say - the command that chef is issuing seems to be identical to what I'm manually doing myself with appcmd.

#### Config after a chef-client run
```xml
<appcmd>
    <CONFIG CONFIG.SECTION="system.webServer/security/authentication/anonymousAuthentication" path="MACHINE/WEBROOT/APPH
OST" overrideMode="Inherit" locked="false">
        <system.webServer-security-authentication-anonymousAuthentication enabled="true" userName="IUSR" />
    </CONFIG>
</appcmd>
```

#### Config after manual unlock
`.\appcmd unlock config -section:"system.webServer/security/authentication/anonymousAuthentication" -commit:apphost`

```xml
<appcmd>
    <CONFIG CONFIG.SECTION="system.webServer/security/authentication/anonymousAuthentication" path="MACHINE/WEBROOT/APPH
OST" overrideMode="Allow" locked="false">
        <system.webServer-security-authentication-anonymousAuthentication enabled="true" userName="IUSR" />
    </CONFIG>
</appcmd>
```

**Comment by tylergohl** [comment]
Here's the chef-client debug output.  Looks like it thinks it is up to date, even though the `overrideMode` is set to `Deny`:

```
  * iis_section[unlocks web.config globally for anonymous auth] action unlock<?xml version="1.0" encoding="UTF-8"?>
<appcmd>
    <CONFIG CONFIG.SECTION="system.webServer/security/authentication/anonymousAuthentication" path="MACHINE/WEBROOT/APP
OST" overrideMode="Deny" locked="false">
        <system.webServer-security-authentication-anonymousAuthentication enabled="true" userName="IUSR" password="" lo
onMethod="ClearText" />
    </CONFIG>
</appcmd> (up to date)
```

**Comment by EasyAsABC123** [comment]
Yay the smell of a bug! I'll dig into the on init check here when I get home.  If you feel inclined you, take a stab at it

Justin Schuhmann

**Comment by EasyAsABC123** [comment]
@tylergohl if you have a moment please look at the pull request #196 it resolves a command bug that might be the issue as to why it isn't even running the unlock command

**Comment by tylergohl** [comment]
Interesting - yes that was the one part of that line that looked off to me.  I'll try it on my end.

**Comment by tylergohl** [comment]
Doesn't look like that fixed it.

I think we might have a logic problem though:

```ruby
action :lock do
  @current_resource.exists = new_value?(doc.root, 'CONFIG/@overrideMode', 'Deny')

  if !@current_resource.exists
    cmd = "#{appcmd(node)} lock config -section:\"#{new_resource.section}\" -commit:apphost"
    Chef::Log.debug(cmd)
    shell_out!(cmd, returns: new_resource.returns)
    new_resource.updated_by_last_action(true)
    Chef::Log.info('IIS Config command run')
  else
    Chef::Log.debug("#{new_resource.section} already locked - nothing to do")
  end
end
```

Correct me if I'm wrong, but shouldn't we either remove the `!` from `!@current_resource.exists` or change the `Deny` to `Allowed` here?

If our anonymous section was set to `Allowed` and we ran this function, `new_value?` would return `true` which `@current_resource.exists` would be set to.  

We would then skip the `If !@current_resource.exists` section, correct?  My ruby is a little lacking but does that sound right?

**Comment by EasyAsABC123** [comment]
@tylergohl agreed, logic changed, please retest

**Comment by tylergohl** [comment]
Works, thanks!

**Comment by EasyAsABC123** [comment]
@tylergohl happy to hear it, @pvandervelde please verify.

After that this issue will be awaiting code review.
