### ISSUE TITLE
Current Master is broken due to rubo-copy changes

### ISSUE THREAD

**Issue by EasyAsABC123** [opscode-cookbooks/iis#163]
I'll need to deeper dive into this to figure out what went wrong, stay tuned.

**Comment by EasyAsABC123** [comment]
please pull - https://github.com/opscode-cookbooks/iis/commit/570761a9eaeaa006192cb2de5cc9994457c87ab5 if you want the current working version.  (The lose of my macbook has slowed my development).

**Comment by EasyAsABC123** [comment]
seems to be working for some and not others, without more information i'm forced to close.

**Comment by ksubrama** [comment]
I think the return: foo syntax is not working depending on the version of ruby that people are using.  If it comes back up, we can re-open it.
