### ISSUE TITLE
Provider pool.rb sytax error in line 280

### ISSUE THREAD

**Issue by keyrage** [opscode-cookbooks/iis#171]
Syntax error in the provider file pool.rb on line 280 within current master branch. Chef run crashes. Suspect "returns" should be ":returns"

[2015-04-29T07:50:37+12:00] ERROR: Converge failed with error message iis_pool[
VenusAppPool] (poal_venuswebsite::default line 12) had an error: NameError: No
resource, method, or local variable named `returns' for `Chef::Provider::IisPoo
l ""'
[2015-04-29T07:50:37+12:00] DEBUG: Re-raising exception: Chef::Exceptions::RunF
ailedWrappingError - Found 1 errors, they are stored in the backtrace
1) NameError -  iis_pool[VenusAppPool] (poal_venuswebsite::default line 12) had
 an error: NameError: No resource, method, or local variable named `returns' fo
r `Chef::Provider::IisPool ""'
  C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:51:in `rescue in me
thod_missing'
  C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:46:in `method_missi
ng'
  C:/chef/cache/cookbooks/iis/providers/pool.rb:280:in `configure_application_p
ool'
  C:/chef/cache/cookbooks/iis/providers/pool.rb:187:in `configure'
  C:/chef/cache/cookbooks/iis/providers/pool.rb:46:in `block in class_from_file
'
  C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:138:in `ins
tance_eval'
  C:/opscode/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:138:in `blo
ck in action'
  C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:149:in `run_action'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels)
 in converge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converg
e'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list
.rb:83:in `block in execute_each_resource'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iter
ator.rb:116:in `call'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iter
ator.rb:116:in `call_iterator_block'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iter
ator.rb:85:in `step'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iter
ator.rb:104:in `iterate'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iter
ator.rb:55:in `each_with_index'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list
.rb:81:in `execute_each_resource'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in conver
ge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_sa
ve'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_g
raceful_exit_option'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in r
un_chef_client'
  C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_
connectivity'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_c
lient'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `blo
ck in interval_run_chef_client'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loo
p'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `int
erval_run_chef_client'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run
_application'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  C:/opscode/chef/bin/chef-client:64:in `load'
  C:/opscode/chef/bin/chef-client:64:in `<main>'

**Comment by keyrage** [comment]
Just pulled latest commits, issue fixed.

**Comment by ksubrama** [comment]
Yay!  Glad to know that the syntax bugfix you submitted resolved it.
