### ISSUE TITLE
iis_pool crashes chef run when setting pipelinemode in current master branch

### ISSUE THREAD

**Issue by keyrage** [opscode-cookbooks/iis#172]
appcmd option for managepiplineMode is being passed incorrect variable (/[name='TestAppPool'].managedPipelineMode:Classic.capitalize")

Backtrace:
iis_pool("TestAppPool") do
  action [:add, :config]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :iis_pool
  cookbook_name "poal_Testwebsite"
  recipe_name "default"
  pipeline_mode :Classic
  thirty_two_bit true
  runtime_version "2.0"
  pool_name "TestAppPool"
  start_mode :OnDemand
  auto_start true
  queue_length 1000
  pool_identity :ApplicationPoolIdentity
  logon_type :LogonBatch
  idle_timeout "00:20:00"
  shutdown_time_limit "00:01:30"
  startup_time_limit "00:01:30"
  pinging_enabled true
  ping_interval "00:00:30"
  ping_response_time "00:01:30"
  load_balancer_capabilities :HttpLevel
  rapid_fail_protection true
  rapid_fail_protection_interval "00:05:00"
  rapid_fail_protection_max_crashes 5
  cpu_action :NoAction
  cpu_limit 0
  cpu_reset_interval "00:05:00"
  smp_processor_affinity_mask 4294967295
  smp_processor_affinity_mask_2 4294967295
end

[2015-04-29T08:56:58+12:00] INFO: Running queued delayed notifications before re-raising exception
[2015-04-29T08:56:58+12:00] ERROR: Converge failed with error message iis_pool[TestAppPool] (poal_Testwebsite::default line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1413'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:applicationPools "/[name='TestAppPool'].autoStart:true" "/[name='TestAppPool'].startMode:OnDemand" "/[name='TestAppPool'].managedRuntimeVersion:v2.0" "/[name='TestAppPool'].managedPipelineMode:Classic.capitalize" "/[name='TestAppPool'].enable32BitAppOnWin64:true" "/[name='TestAppPool'].queueLength:1000" "/[name='TestAppPool'].processModel.maxProcesses:" "/[name='TestAppPool'].processModel.loadUserProfile:false" "/[name='TestAppPool'].processModel.logonType:LogonBatch" "/[name='TestAppPool'].processModel.manualGroupMembership:false" "/[name='TestAppPool'].processModel.idleTimeout:00:20:00" "/[name='TestAppPool'].processModel.shutdownTimeLimit:00:01:30" "/[name='TestAppPool'].processModel.startupTimeLimit:00:01:30" "/[name='TestAppPool'].processModel.pingingEnabled:true" "/[name='TestAppPool'].processModel.pingInterval:00:00:30" "/[name='TestAppPool'].processModel.pingResponseTime:00:01:30" "/[name='TestAppPool'].recycling.periodicRestart.time:" "/+[name='TestAppPool'].recycling.periodicRestart.schedule.[value='']" "/[name='TestAppPool'].recycling.logEventOnRecycle:PrivateMemory,Memory,Schedule,Requests,Time,ConfigChange,OnDemand,IsapiUnhealthy" "/[name='TestAppPool'].recycling.periodicRestart.privateMemory:" "/[name='TestAppPool'].recycling.disallowRotationOnConfigChange:false" "/[name='TestAppPool'].recycling.disallowOverlappingRotation:false" "/[name='TestAppPool'].failure.loadBalancerCapabilities:HttpLevel" "/[name='TestAppPool'].failure.orphanWorkerProcess:false" "/[name='TestAppPool'].failure.orphanActionExe:" "/[name='TestAppPool'].failure.orphanActionParams:" "/[name='TestAppPool'].failure.rapidFailProtection:true" "/[name='TestAppPool'].failure.rapidFailProtectionInterval:00:05:00" "/[name='TestAppPool'].failure.rapidFailProtectionMaxCrashes:5" "/[name='TestAppPool'].failure.autoShutdownExe:" "/[name='TestAppPool'].failure.autoShutdownParams:" "/[name='TestAppPool'].cpu.action:NoAction" "/[name='TestAppPool'].cpu.limit:0" "/[name='TestAppPool'].cpu.resetInterval:00:05:00" "/[name='TestAppPool'].cpu.smpAffinitized:false" "/[name='TestAppPool'].cpu.smpProcessorAffinityMask:4294967295" "/[name='TestAppPool'].cpu.smpProcessorAffinityMask2:4294967295" ----
STDOUT: ERROR ( message:Unknown attribute "managedPipelineMode".. Reason: Enum must be one of Integrated, Classic

**Comment by EasyAsABC123** [comment]
good catch, fixing it right now

**Comment by EasyAsABC123** [comment]
please test #175

**Comment by keyrage** [comment]
Looks good.
