### ISSUE TITLE
iis_pool resource fails on coverge due to appcmd time attribute not of the correct format.

### ISSUE THREAD

**Issue by keyrage** [opscode-cookbooks/iis#173]
Current master branch has a fault where the configuration of an app pool fails due to the appcmd call passing a time attribute with a blank string which fails the appcmd with error code 13.

Backtrace:
Resource Declaration:
---------------------
# In C:/chef/cache/cookbooks/poal_Testwebsite/recipes/default.rb

 12: iis_pool "#{node['poal_Testwebsite']['app_pool']}" do
 13:   action [:add,:config]
 14:   pipeline_mode node['poal_Testwebsite']['pipelinemode']
 15:   thirty_two_bit node['poal_Testwebsite']['thirty_two_bit']
 16:   runtime_version node['poal_Testwebsite']['app_pool_dotnetversion']
 17: end
 18: 

Compiled Resource:
------------------
# Declared in C:/chef/cache/cookbooks/poal_Testwebsite/recipes/default.rb:12:in `from_file'

iis_pool("TestAppPool") do
  action [:add, :config]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :iis_pool
  cookbook_name "poal_Testwebsite"
  recipe_name "default"
  pipeline_mode :Classic
  thirty_two_bit true
  runtime_version "2.0"
  pool_name "TestAppPool"
  start_mode :OnDemand
  auto_start true
  queue_length 1000
  pool_identity :ApplicationPoolIdentity
  logon_type :LogonBatch
  idle_timeout "00:20:00"
  shutdown_time_limit "00:01:30"
  startup_time_limit "00:01:30"
  pinging_enabled true
  ping_interval "00:00:30"
  ping_response_time "00:01:30"
  load_balancer_capabilities :HttpLevel
  rapid_fail_protection true
  rapid_fail_protection_interval "00:05:00"
  rapid_fail_protection_max_crashes 5
  cpu_action :NoAction
  cpu_limit 0
  cpu_reset_interval "00:05:00"
  smp_processor_affinity_mask 4294967295
  smp_processor_affinity_mask_2 4294967295
end

[2015-04-29T09:10:26+12:00] INFO: Running queued delayed notifications before re-raising exception
[2015-04-29T09:10:26+12:00] ERROR: Converge failed with error message iis_pool[TestAppPool] (poal_Testwebsite::default line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '13'
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:applicationPools "/[name='TestAppPool'].autoStart:true" "/[name='TestAppPool'].startMode:OnDemand" "/[name='TestAppPool'].managedRuntimeVersion:v2.0" "/[name='TestAppPool'].managedPipelineMode:Classic" "/[name='TestAppPool'].enable32BitAppOnWin64:true" "/[name='TestAppPool'].queueLength:1000" "/[name='TestAppPool'].processModel.maxProcesses:" "/[name='TestAppPool'].processModel.loadUserProfile:false" "/[name='TestAppPool'].processModel.logonType:LogonBatch" "/[name='TestAppPool'].processModel.manualGroupMembership:false" "/[name='TestAppPool'].processModel.idleTimeout:00:20:00" "/[name='TestAppPool'].processModel.shutdownTimeLimit:00:01:30" "/[name='TestAppPool'].processModel.startupTimeLimit:00:01:30" "/[name='TestAppPool'].processModel.pingingEnabled:true" "/[name='TestAppPool'].processModel.pingInterval:00:00:30" "/[name='TestAppPool'].processModel.pingResponseTime:00:01:30" "/[name='TestAppPool'].recycling.periodicRestart.time:" "/+[name='TestAppPool'].recycling.periodicRestart.schedule.[value='']" "/[name='TestAppPool'].recycling.logEventOnRecycle:PrivateMemory,Memory,Schedule,Requests,Time,ConfigChange,OnDemand,IsapiUnhealthy" "/[name='TestAppPool'].recycling.periodicRestart.privateMemory:" "/[name='TestAppPool'].recycling.disallowRotationOnConfigChange:false" "/[name='TestAppPool'].recycling.disallowOverlappingRotation:false" "/[name='TestAppPool'].failure.loadBalancerCapabilities:HttpLevel" "/[name='TestAppPool'].failure.orphanWorkerProcess:false" "/[name='TestAppPool'].failure.orphanActionExe:" "/[name='TestAppPool'].failure.orphanActionParams:" "/[name='TestAppPool'].failure.rapidFailProtection:true" "/[name='TestAppPool'].failure.rapidFailProtectionInterval:00:05:00" "/[name='TestAppPool'].failure.rapidFailProtectionMaxCrashes:5" "/[name='TestAppPool'].failure.autoShutdownExe:" "/[name='TestAppPool'].failure.autoShutdownParams:" "/[name='TestAppPool'].cpu.action:NoAction" "/[name='TestAppPool'].cpu.limit:0" "/[name='TestAppPool'].cpu.resetInterval:00:05:00" "/[name='TestAppPool'].cpu.smpAffinitized:false" "/[name='TestAppPool'].cpu.smpProcessorAffinityMask:4294967295" "/[name='TestAppPool'].cpu.smpProcessorAffinityMask2:4294967295" ----
STDOUT: ERROR ( message:Can not set attribute "time" to value "".. Reason: Timespan must be of form [-][d.]hh:mm:ss[.ff]

**Comment by EasyAsABC123** [comment]
this just needs to be `is_new_or_empty?` since it shouldn't do anything if it is empty.

Good catch

**Comment by EasyAsABC123** [comment]
from what i can tell it already uses `is_new_or_empty?` and the code looks right...curious

**Comment by keyrage** [comment]
Looking at the backtrace above and the helper.rb code, I'm kind of wondering if the logic in new_or_empty_value? and new_value? is correct. My complete lack of Ruby knowledge is limiting me here. Every property of the pool is being set on every run even if there is no change to it.

**Comment by EasyAsABC123** [comment]
this is because someone changed `return` to `:returns` in `configure_application_pool`...by someone i mean likely me

**Comment by EasyAsABC123** [comment]
please add #176 to test (it fixes this)...now off to bindings

**Comment by keyrage** [comment]
Looks good.
