### ISSUE TITLE
iis_site resource throws error "NomethodError: undefined method 'bindings='

### ISSUE THREAD

**Issue by keyrage** [opscode-cookbooks/iis#174]
iis_site throws an error "NoMethodError: undefined method `bindings=' for Chef::Resource::IisSite"

Backtrace:
[2015-04-29T09:21:00+12:00] DEBUG: iis_site[Test] current_resource match output: SITE "Test" (id:1,bindings:http/*:80:,state:Started)

================================================================================
Error executing action `config` on resource 'iis_site[Test]'
================================================================================

NoMethodError
-------------
undefined method `bindings=' for Chef::Resource::IisSite

Resource Declaration:
---------------------
# In C:/chef/cache/cookbooks/poal_Testwebsite/recipes/default.rb

 62: iis_site "#{node['poal_Testwebsite']['website']}" do
 63:   protocol  :http
 64:   port 80
 65:   path "#{node['iis']['docroot']}\\#{node['poal_Testwebsite']['phypath']}\\Sandfield.WorkWith.Web"
 66:   host_header ""
 67:   application_pool "#{node['poal_Testwebsite']['app_pool']}"
 68:   action  [:add,:config]
 69: end
 70: 

Compiled Resource:
------------------
# Declared in C:/chef/cache/cookbooks/poal_Testwebsite/recipes/default.rb:62:in `from_file'

iis_site("Test") do
  action [:add, :config]
  updated true
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :iis_site
  cookbook_name "poal_Testwebsite"
  recipe_name "default"
  protocol :http
  port 80
  path "C:\\inetpub\\wwwroot\\Test\\Sandfield.WorkWith.Web"
  application_pool "TestAppPool"
  site_name "Test"
  log_directory "C:\\inetpub\\logs\\LogFiles"
  log_period :Daily
  log_truncsize 1048576
end

[2015-04-29T09:21:00+12:00] INFO: Running queued delayed notifications before re-raising exception
[2015-04-29T09:21:00+12:00] ERROR: Converge failed with error message iis_site[Test] (poal_Testwebsite::default line 62) had an error: NoMethodError: undefined method `bindings=' for Chef::Resource::IisSite
[2015-04-29T09:21:00+12:00] DEBUG: Re-raising exception: Chef::Exceptions::RunFailedWrappingError - Found 1 errors, they are stored in the backtrace
1) NoMethodError -  iis_site[Test] (poal_Testwebsite::default line 62) had an error: NoMethodError: undefined method `bindings=' for Chef::Resource::IisSite
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:959:in `method_missing'
  C:/chef/cache/cookbooks/iis/providers/site.rb:117:in `load_current_resource'
  C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:128:in `run_action'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
  C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
  C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
  C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  C:/opscode/chef/bin/chef-client:64:in `load'
  C:/opscode/chef/bin/chef-client:64:in `<main>'

**Comment by EasyAsABC123** [comment]
this is in the latest master?

**Comment by keyrage** [comment]
As of when I logged the issue it was. I remarked out that line 117 and it all worked.

**Comment by EasyAsABC123** [comment]
@keyrage debugging right now, first the other issue then this one.

**Comment by EasyAsABC123** [comment]
Okay, this happens because you are setting:
```ruby
protocol :http
port 80
host_header ""
```

looking to fix this bug now

**Comment by EasyAsABC123** [comment]
I have the fix for this but I can't publish...

Change Line 117 to in providers/site.rb: 
```ruby
@current_resource.bindings(result[3])
```

**Comment by EasyAsABC123** [comment]
there done, please test #177 this will resolve this bug (you need all three to "work)

**Comment by keyrage** [comment]
Looks good, really that was my stuff up for putting a blank host_header attribute in there in the first place, had put it in as a placeholder for wehn/if I needed to set it..
