### ISSUE TITLE
Promote current master branch to version 4.1.1

### ISSUE THREAD

**Issue by keyrage** [opscode-cookbooks/iis#178]
Hi,

I don't know what the full process is but the fixes in the master build are important enough that I'd be keen to see the cookbook version bumped to 4.1.1 and shipped to the supermarket. Since it fixes at least one bug that will get hit by users pretty regularly it would be good to stop others pulling 4.1 down.

**Comment by EasyAsABC123** [comment]
I leave releases to the good folks at chef, but i know @ksubrama will knock that out.

**Comment by ksubrama** [comment]
Hey!  I will get to a release next week after doing some quick sanity checking.

**Comment by EasyAsABC123** [comment]
Sounds good, I'll likely be making a new branch for refactoring and iis_root provider.  I figure it should be marked as a minor or major so I'd like to see a stable v4. :)
