### ISSUE TITLE
Pipeline mode is not idempotent

### ISSUE THREAD

**Issue by Scythril** [opscode-cookbooks/iis#179]
I have a bunch of app pools' pipeline_mode set to :Integrated, but it appears that the cookbook is trying to set it every time (based on debug logs). My assumption is that the check whether it's already set isn't correct, or not checking at all.

**Comment by EasyAsABC123** [comment]
providers/pool.rb - line 134
it appears to be caused by the following line:
```ruby
    is_new_pipeline_mode = new_value?(doc.root, 'APPPOOL/@PipelineMode'.capitalize, "#{new_resource.pipeline_mode}".to_s.capitalize)
```
This should be:
```ruby
    is_new_pipeline_mode = new_value?(doc.root, 'APPPOOL/@PipelineMode', "#{new_resource.pipeline_mode}")
```

If you could change this line locally and then test (I'll test it when I get home).

**Comment by Scythril** [comment]
Almost. `new_resource.pipeline_mode` is a Symbol, not a string, so that was one part of the issue. The other part was what you mentioned, the capitalization wasn't done properly (I see the intent, so I just fixed the execution).

**Comment by EasyAsABC123** [comment]
Don't need to do the capitalize or downcase.  It works fine without it since he symbols have proper casing.  Please just change the one line

Justin Schuhmann

**Comment by Scythril** [comment]
Ok. I still had to drop the quotes because it was including the colon in the string, but it works.
