### ISSUE TITLE
IIS App Pool recycle schedule question

### ISSUE THREAD

**Issue by kkennedy1** [opscode-cookbooks/iis#190]
Hi,

We're using IIS cookbook 4.1.0 and have a question about the behavior of setting an app pool reschedule time.  We are using the 'recycle_at_time' setting to set it, but have found that if there multiple scheduled recycle times already configured for the app pool, they will not be cleared out before setting the value.  I *think* the desired behavior would be that if the existing scheduled time is different that what we're setting it to, or there are more than one scheduled time configured, we would want to clear out all schedules, then set the value.  Otherwise, do nothing.  I was hoping to get your thoughts on it.  We'd be happy to supply a pull request if that's the desired behavior.

Thanks!

Kevin

**Comment by EasyAsABC123** [comment]
@kkennedy1 I will have to take a look at it to see if you are correct.  From this short description I think you are

Justin Schuhmann

**Comment by EasyAsABC123** [comment]
yes, it appears that it should destroy any previous schedule based on:

```ruby
      cmd = "#{appcmd(node)} set config /section:applicationPools \"/-[name='#{new_resource.pool_name}'].recycling.periodicRestart.schedule\""
```

**Comment by kkennedy1** [comment]
Ok great, thanks for checking, that’s what we thought.  In the case that there is more than one time scheduled and the recycle time we want to set already exists, it won’t clear them out.  We have a proposed fix and would like to submit a pull request.

**Comment by EasyAsABC123** [comment]
Feel free to submit! 

Justin Schuhmann

**Comment by EasyAsABC123** [comment]
resolved with merge
