### ISSUE TITLE
IIS App Pool recycle schedule in pool.rb

### ISSUE THREAD

**Issue by kkennedy1** [opscode-cookbooks/iis#192]
This is related to issue #190.  With the recent commit, the problem of being able to determine if the app pool recycle schedule exists works, but if there is more than one schedule configured, for example if someone manually added one, the schedules aren't cleared out.  I have an update to clear out the schedules before setting in the following cases:
- There is more than one recycle schedule set on the app pool
- The time we're setting is a new time.

**Comment by EasyAsABC123** [comment]
closed with merge
