### ISSUE TITLE
Testfu example is not clear

### ISSUE THREAD

**Issue by scarolan** [opscode-cookbooks/iis#197]
New users might not understand that they have to create the 'testfu' directory first for this to work. Maybe some clarification that the dir must exist would be helpful.

# create and start a new site that maps to
# the physical location C:\inetpub\wwwroot\testfu
iis_site 'Testfu Site' do
  protocol :http
  port 80
  path "#{node['iis']['docroot']}/testfu"
  action [:add,:start]
end

**Comment by EasyAsABC123** [comment]
fixed in commit https://github.com/opscode-cookbooks/iis/commit/7128a32904afa092b231dda62c317daf03d91a2e#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by scarolan** [comment]
thank you!!!

**Comment by EasyAsABC123** [comment]
@scarolan never a problem, good call too it definitely is a gotcha :+1:...at one point i was going to auto create the application pool and the directory if it didn't exist...then i think i didn't like that i was doing auto-magic...

Definitely something that should of been documented.
