### ISSUE TITLE
Can cookbook set authentication

### ISSUE THREAD

**Issue by spuder** [opscode-cookbooks/iis#201]
Can this cookbook set authentication? 

<img width="574" alt="screenshot 2015-08-11 10 10 55" src="https://cloud.githubusercontent.com/assets/242382/9203465/93190324-4014-11e5-9c3e-616e0f6a72fc.png">

I can't tell from the readme if you can set this.

If its not possible, I'd like to open a feature request. 
If it is possible, I'm happy to edit the docs once I figure it out.

**Comment by spuder** [comment]
Sorry for the noise, turns out to be easier than I thought. Documentation improvement on the way. 

http://debugging.io/weblog/post/Powershell-how-to-to-change-the-anonymous-identity(IUSR)-to-application-pool-identity-of-an-IIS-website

http://forums.iis.net/t/1152524.aspx?AppCMD+with+anonymous+Authentication

```bash
#powershell
# Default IUSR_website user
C:\Windows\System32\inetsrv\appcmd.exe set config "MyWebsite" -section:system.webServer/security/authentication/anonymousAuthentication /enabled:"True" /userName:"IUSR_website" /password:"p@assword" /commit:apphost
```

```ruby
#chef
iis_config "\"MyWebsite\" -section:system.webServer/security/authentication/anonymousAuthentication /enabled:\"True\" /userName:\"IUSR_website\" /password:\"p@assword\" /commit:apphost" do
  action :config
end
```

Application pool identity

```bash
#powershell
 C:\Windows\System32\inetsrv\appcmd.exe set config "MyWebsite" -section:system.webServer/security/authentication/anonymousAuthentication /enabled:"True" /userName:"" /commit:apphost
```

```ruby
#chef
iis_config "\"MyWebsite\" -section:system.webServer/security/authentication/anonymousAuthentication /enabled:\"True\" /userName:\"\" /commit:apphost" do
   action :config
end
```

**Comment by EasyAsABC123** [comment]
I believe it is built into the iis_apppool provider I'll look when I can

Justin Schuhmann

**Comment by EasyAsABC123** [comment]
Ah this is suppose to be built into the iis_section but it doesn't work currently.

**Comment by spuder** [comment]
oh? The above examples work for me (and are natively idempotent) 

The only thing it doesn't do is restart IIS (not sure if that is actually need though)
