### ISSUE TITLE
Specifying multiple bindings on the same port and ip

### ISSUE THREAD

**Issue by developingchris** [opscode-cookbooks/iis#62]
I'm trying to setup a site that has 2 80 and 443 bindings, for a total of 4.

<fqdn>.beta.a.com
www.beta.a.com

This way we can have it load balanced and singularly accessed.
I keep getting syntax errors in the iis_site resource doing this. Either I'm missing something or it would be nice to have an iis_binding resource.  I've created one but wonder if this is just me brute forcing it to work, while not understanding how to do multiple bindings in the site properly.

Anyone want this?

**Comment by EasyAsABC123** [comment]
@christrotter is this still not resolved?

**Comment by christrotter** [comment]
The bindings option is working with the branch you gave me, so I'm good from this issue's point-of-view.
