### ISSUE TITLE
Could iis_app support setting the Requires SSL flag ?

### ISSUE THREAD

**Issue by rlaveycal** [opscode-cookbooks/iis#67]
Could support for setting the Require SSL setting be added:

http://technet.microsoft.com/en-us/library/cc732367%28v=ws.10%29.aspx 

Thanks

**Comment by EasyAsABC123** [comment]
@rlaveycal from the link provided:

To require SSL, use the following syntax:
```
appcmd set config " site | URL " /section: access /sslFlags:Ssl /commit:APPHOST
```
The variable site | URL is the site, application, virtual directory, or file where you want IIS 7 to require SSL. For example, to require SSL for the Default Web Site, type the following at the command prompt, and then press ENTER:
```
appcmd set config " Default Web Site " /section: access /sslFlags:Ssl /commit:APPHOST
```

To require SSL for the file iisstart.htm on the Default Web Site, type the following at the command prompt, and then press ENTER:
```
appcmd set config " http://localhost/iisstart.htm " /section: access /sslFlags:Ssl /commit:APPHOST
```

all of these commands can be done via the `iis_config` provider

**Comment by EasyAsABC123** [comment]
@smurawski I believe the above shows this isn't an issue
