### ISSUE TITLE
iis_config resource is not idempotent

### ISSUE THREAD

**Issue by aaronrl** [opscode-cookbooks/iis#69]
The IIS_config resource is not idempotent. It will try to apply the same config twice, even if that config is already true. This could result in non-zero output on subsequent runs in the event that a config has already been applied, even though there is nothing wrong with the system state.

Text copied from:
https://tickets.opscode.com/browse/COOK-4359

Example that will fail when client is ran >1 time:
iis_config "/section:httpProtocol /-customHeaders.[name='X-Powered-By']" do
  action :config
end

Current implementation of iis_config requires a guard to achieve idempotence.

**Comment by EasyAsABC123** [comment]
@smurawski should this be closed?

**Comment by domenicomusto** [comment]
Hello,

I'm still having this issue with the following 

iis_config '/section:system.webServer/proxy /enabled:"true"' do
  action :set
end

The configuration change gets always applied even if the proxy has already been enabled

**Comment by EasyAsABC123** [comment]
@domenicomusto iis_config is not idempotent thereby it will always get applied unless you add a if statement to your own receipt.

**Comment by domenicomusto** [comment]
Thanks @EasyAsABC123, is there any other resource I can use to check if that config is been set already so I can keep my cookbook idempotent ? Thanks

**Comment by EasyAsABC123** [comment]
@domenicomusto you'll need to basically run some PowerShell that pulls back the value of the setting and doesn't run the code if it is set to X.
```ruby
iis_config '/section:system.webServer/proxy /enabled:"true"' do
    action :set
    not_if do PowerShellCmd == 'X' end
end
```
