### ISSUE TITLE
pool provider prints app pool password

### ISSUE THREAD

**Issue by dvanbuskirk** [opscode-cookbooks/iis#76]
https://github.com/opscode-cookbooks/iis/blob/master/providers/pool.rb#L89

The password is printed in chef debug mode.  This password needs to remain secure and out of sight regardless of log level.

**Comment by EasyAsABC123** [comment]
@dvanbuskirk this can definitely be fixed
https://github.com/opscode-cookbooks/iis/blob/master/providers/pool.rb#L222

but do you think hiding the password when running chef in debug mode is wise? what if the issue has something to do with the characters in the password?  It is a simple task to remove the password that is used from the command if it is agreed that for security purposes this should be done.

**Comment by smurawski** [comment]
It should be fixed, despite IIS configuration being as solid as swiss cheese when it comes to app pool passwords.

Any of the IIS management models return the app pool passwords in clear text. :(  
Example - using the WebAdministration module run
```(Get-ItemProperty IIS:\AppPools\SomeAppPoolName).ProcessModel ```

**Comment by christrotter** [comment]
Wow.  Thanks for that one-liner @smurawski ...crazy.

**Comment by EasyAsABC123** [comment]
This looks resolved :+1:
