### ISSUE TITLE
Many of the Attributes won't be applied when adding a new app pool.

### ISSUE THREAD

**Issue by mdw233** [opscode-cookbooks/iis#77]
See https://github.com/opscode-cookbooks/iis/blob/master/providers/pool.rb#L42

The Attributes in this section of the iis_pool resource are not applied when adding a new app pool, unless you also specify the :config action.  I'd expect those attributed to be applied without having to specify the config option.

The following gist illustrates the issue with an example: https://gist.github.com/mdw233/b38016059753dae54941

Is this intended, or an oversight?  If it's intended - I can add a PR to make it more clear in the docs.

**Comment by christrotter** [comment]
I'm attempting to use the iis_pool attributes, not having any luck with the user/pass settings, but not getting any errors, either.

Using:
1. chef-server 12.0.1
2. chef-client 11.14.2-1
3. node is Win2008R2
4. IIS is 3.0.5 from EasyAsABC123's hotfix branch

``` ruby
 iis_pool "#{cookbook_name}" do
     runtime_version "4.0"
     pipeline_mode :Integrated
     pool_username "domain\\username"
     pool_password "password"
     action [:add, :config]
 end
```

I also tried variants - no errors, but does not apply, either.
``` ruby
pool_username "username"
pool_username 'domain\username'

# And tried separating out the pool_user/pass into a dedicated :config section...
```

Any ideas?

**Comment by EasyAsABC123** [comment]
@christrotter appears to be a bug introduced in #91 that made this feature not work at all in `:add` or `:config`, please get iis@3.0.6 from my hotfix branch.  this issue should be resolved, also verify other settings are working.

**Comment by EasyAsABC123** [comment]
any news on this @christrotter ?

**Comment by christrotter** [comment]
Will test it out today, sorry for the delay.

**Comment by EasyAsABC123** [comment]
@christrotter please don't be sorry, just making sure this is all cleaned up for everyone so that I can pursue the pull request.  Thanks for your hard work and testing, without it this new version would never see release status.

**Comment by christrotter** [comment]
So it's working, but not for domain names.  I removed both the site and appPool, tried again - this worked!  So maybe the code isn't allowing for changing an existing username?

Code I tried with first: (was leftover from earlier testing)
``` ruby
 #creates a new app pool
 iis_pool "#{cookbook_name}" do
     runtime_version "4.0"
     pipeline_mode :Integrated
	 pool_username "username"
 	 pool_password "password"
     action [:add, :config]
 end
```

Code changed to: (added in "domain\\")
``` ruby
 #creates a new app pool
 iis_pool "#{cookbook_name}" do
     runtime_version "4.0"
     pipeline_mode :Integrated
	 pool_username "domain\\username"
 	 pool_password "password"
     action [:add, :config]
 end
```

Doing some functional testing now...

**Comment by christrotter** [comment]
Yeah, looks like it's working.  Thanks again!  I'll open a new issue if something else comes up.

**Comment by EasyAsABC123** [comment]
@christrotter testing username changing, not sure what that might be.

**Comment by EasyAsABC123** [comment]
@christrotter doesn't appear to be a bug, when doing Domain Name change only you won't notice a difference when looking at the iis settings manually.

**Comment by christrotter** [comment]
Great, thanks for checking.  I think we're good!

**Comment by EasyAsABC123** [comment]
@smurawski should this be closed?
