### ISSUE TITLE
iis_config fails with certain commands

### ISSUE THREAD

**Issue by kbarry-x** [opscode-cookbooks/iis#89]
I'd love someone else to verify this:

```
iis_config "-section:system.webServer/handlers /[name=\'ExtensionlessUrlHandler-Integrated-4.0\'].verb:\"GET,HEAD,POST,DEBUG,PUT,DELETE\"  /commit:apphost" do
    action :config
end
```

getting this error
```
==> default: Ran 
C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/handlers /[name='ExtensionlessUrlHandler-Integrated-4.0'].verb:"GET,HEAD,POST,DEBUG,PUT,DELETE"  /commit:apphost returned 4312
```

Running the command it says it ran works...... 
```
C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/handlers /[name='ExtensionlessUrlHandler-Integrated-4.0'].verb:"GET,HEAD,POST,DEBUG,PUT,DELETE"  /commit:apphost
```

**Comment by webframp** [comment]
Saw something similar with this snippet in a recipe:

```rb
  iis_config "/section:staticContent /+\"[fileExtension='.gem',mimeType='application/octet-stream ']\"" do
    action :config
  end
```

```
---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:staticContent /+"[fileExtension='.gem',mimeType='application/octet-stream ']" ----
STDOUT: ERROR ( message:New mimeMap object missing required attributes. Cannot add duplicate collection entry of type 'mimeMap' with unique key attribute 'fileExtension' set to '.gem'. )
STDERR:
---- End output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:staticContent /+"[fileExtension='.gem',mimeType='application/octet-stream ']" ----
Ran C:\Windows\System32\inetsrv\appcmd.exe set config /section:staticContent /+"[fileExtension='.gem',mimeType='application/octet-stream ']" returned 183
```
This worked the first time it ran. It could just be my ignorance with how appcmd work, but it seems like maybe the resource isn't really idempotent in some cases?

chef-client 11.16.2, iis version 7.5 and iis cookbook version 2.1.6

**Comment by kbarry-x** [comment]
In '/+"[fileExtension .... ' the "+" means "Add", exit 183 means "This
already exists, you can't add it again"

You can change the expected exit codes to include 183, as its not really a
bad exit, it simply means "I am already there".

On Wed, Jan 28, 2015 at 1:40 PM, Sean Escriva <notifications@github.com>
wrote:

> Saw something similar with this snippet in a recipe:
>
>   iis_config "/section:staticContent /+\"[fileExtension='.gem',mimeType='application/octet-stream ']\"" do
>     action :config
>   end
>
> ---- Begin output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:staticContent /+"[fileExtension='.gem',mimeType='application/octet-stream ']" ----
> STDOUT: ERROR ( message:New mimeMap object missing required attributes. Cannot add duplicate collection entry of type 'mimeMap' with unique key attribute 'fileExtension' set to '.gem'. )
> STDERR:
> ---- End output of C:\Windows\System32\inetsrv\appcmd.exe set config /section:staticContent /+"[fileExtension='.gem',mimeType='application/octet-stream ']" ----
> Ran C:\Windows\System32\inetsrv\appcmd.exe set config /section:staticContent /+"[fileExtension='.gem',mimeType='application/octet-stream ']" returned 183
>
> This worked the first time it ran. It could just be my ignorance with how
> appcmd work, but it seems like maybe the resource isn't really idempotent
> in some cases?
>
> chef-client 11.16.2, iis version 7.5 and iis cookbook version 2.1.6
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opscode-cookbooks/iis/issues/89#issuecomment-71922057>
> .
>



-- 

Kenneth Barry
TuneIn | Build and Release Engineer
M: 409-673-0544
www.tunein.com

**Comment by EasyAsABC123** [comment]
@webframp since you can run anything and everything via iis_config it can't really be idempotent...it is going to run everytime chef-client runs.

```ruby
require 'chef/mixin/shell_out'

include Chef::Mixin::ShellOut
include Opscode::IIS::Helper

action :config do
  cmd = "#{appcmd(node)} set config #{@new_resource.cfg_cmd}"
  Chef::Log.debug(cmd)
  shell_out!(cmd, :returns => @new_resource.returns)
  Chef::Log.info("IIS Config command run")
  @new_resource.updated_by_last_action(true)
end
```
this is all there is to the iis_config provider

@kbarry-x adding 183 doesn't look like a bad idea at all, let me think on it and see if I can find an issue.
one other solution would be make it accept any error (since it just runs anything given to it)...trying to make it idempotent is an impossible task I believe...

good find though

**Comment by kbarry-x** [comment]
I was not using the latest version of the cookbook. I am getting the latest version now. When I attempted to earlier, I ran into https://github.com/opscode-cookbooks/iis/issues/95

I am updating, and testing now. Wish me luck.

**Comment by ksubrama** [comment]
The /+ config commands are currently not idempotent and I think there is some lingering issue in detecting them correctly.  Let me know if the newest version works for you.  If not, I'll keep an careful eye for this when doing a bug-fix pass.

**Comment by kbarry-x** [comment]
I'm still getting the erro, using the latest of both the windows and iis cookbooks.

I'm going to change

resources/config.rb

attribute :returns, :kind_of => [Integer, Array], :default => 0
to
attribute :returns, :kind_of => [Integer, Array], :default => [0,183]

**Comment by EasyAsABC123** [comment]
@kbarry-x please test that and submit a pull request.

**Comment by kbarry-x** [comment]
183 is the "Its already there" code. And i believe it was a hack/fix in a
previous version employed by others. Lemme see if I can figure out a
pull-request ;)

On Tue, Mar 31, 2015 at 12:11 PM, Justin Schuhmann <notifications@github.com
> wrote:

> @kbarry-x <https://github.com/kbarry-x> please test that and submit a
> pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opscode-cookbooks/iis/issues/89#issuecomment-88212609>
> .
>



-- 

Kenneth Barry
TuneIn | Build and Release Engineer
M: 409-673-0544
www.tunein.com

**Comment by EasyAsABC123** [comment]
Actually this isn't a pull request, here is the solution...

add an attribute to your provider call

```ruby
iis_config "-section:system.webServer/handlers /[name=\'ExtensionlessUrlHandler-Integrated-4.0\'].verb:\"GET,HEAD,POST,DEBUG,PUT,DELETE\"  /commit:apphost" do
    action :config
    returns [0, 183]
end
```

A global change isn't a great idea here but this will definitely solve your use case.

**Comment by kbarry-x** [comment]
Awesome. Thanks very much. I wasnt aware of "returns" but I suspect its a
"common attribute"


On Tue, Mar 31, 2015 at 1:29 PM, Justin Schuhmann <notifications@github.com>
wrote:

> Actually this isn't a pull request, here is the solution...
>
> add an attribute to your provider call
>
> iis_config "-section:system.webServer/handlers /[name=\'ExtensionlessUrlHandler-Integrated-4.0\'].verb:\"GET,HEAD,POST,DEBUG,PUT,DELETE\"  /commit:apphost" do
>     action :config
>     returns [0, 183]end
>
> A global change isn't a great idea here but this will definitely solve
> your use case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opscode-cookbooks/iis/issues/89#issuecomment-88234613>
> .
>



-- 

Kenneth Barry
TuneIn | Build and Release Engineer
M: 409-673-0544
www.tunein.com

**Comment by EasyAsABC123** [comment]
@kbarry-x never a problem, this is definitely a permanent solution for you.  We just need to decide if that's the permanent solution for everyone via default.

**Comment by kbarry-x** [comment]
How do we handle configs that are in the form of an  "addition"?
On Tue, Mar 31, 2015 at 3:10 PM, Justin Schuhmann <notifications@github.com>
wrote:

> @kbarry-x <https://github.com/kbarry-x> never a problem, this is
> definitely a permanent solution for you. We just need to decide if that's
> the permanent solution for everyone via default.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opscode-cookbooks/iis/issues/89#issuecomment-88268112>
> .
>



-- 

Kenneth Barry
TuneIn | Build and Release Engineer
M: 409-673-0544
www.tunein.com

**Comment by EasyAsABC123** [comment]
@kbarry-x can you provide an example?

**Comment by EasyAsABC123** [comment]
@kbarry-x Closing issue, appears to be resolved.  If you have an example of the issue persisting please re-open.  Thanks
